#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and catches SIGTERM (15) to print "I am invincible!!!".
# <--- Ensure this line starts with a '#'
handle_sigterm() {
    printf "I am invincible!!!\n"
}

trap 'handle_sigterm' 15

while true
do
    echo "To infinity and beyond"
    sleep 2
done
